### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by marooncn** [pemami4911/neural-combinatorial-rl-pytorch#6]
Hi, when I run 
`python3 trainer.py `
There comes an error: 
> Traceback (most recent call last):
  File "trainer.py", line 203, in <module>
    R, probs, actions, actions_idxs = model(bat)
  File "/home/maroon/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/maroon/PycharmProjects/neural-combinatorial-rl-pytorch/neural_combinatorial_rl.py", line 539, in forward
    R = self.objective_fn(actions, self.use_cuda)
  File "/home/maroon/PycharmProjects/neural-combinatorial-rl-pytorch/sorting_task.py", line 49, in reward
    current += res.float()  
RuntimeError: invalid argument 1: the number of sizes provided must be greater or equal to the number of dimensions in the tensor at /pytorch/torch/lib/TH/generic/THTensor.c:299

How can I solve it? Thank you.

**Comment by maltedeckers** [comment]
Hi, I had the same issue, using PyTorch 0.4.0.
Maybe my solution in my fork (https://github.com/mteser/neural-combinatorial-rl-pytorch) works for you, too?

**Comment by pemami4911** [comment]
This is an issue due to using PyTorch 0.3 (previously, this code was only compatible with PyTorch 0.2). The `master` branch should now work with both 0.2 and 0.3.
